from pydantic import BaseModel, Field

class QueryRequest(BaseModel):
    """
    Standard schema for agent incoming query requests.
    """
    query: str = Field(..., description="The user query or prompt.")

class QueryResponse(BaseModel):
    """
    Standard schema for agent responses returned to the UI.
    """
    response: str = Field(..., description="The textual response generated by the agent.")
    framework_used: str = Field(..., description="The agent framework used (crewai, langgraph, autogen, beeai).")
