from __future__ import annotations
from typing import List, Optional
from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    """Standard schema for agent incoming query requests."""
    query: str = Field(..., description="The user query or prompt.")


class QueryResponse(BaseModel):
    """Standard schema for agent responses returned to the UI."""
    response: str = Field(..., description="The textual response generated by the agent.")
    framework_used: str = Field(..., description="The agent framework used (crewai, langgraph, autogen, beeai).")


class PlannerOutput(BaseModel):
    """
    Output schema for the Planner Agent.
    Describes the sub-tasks derived from the user query, detected category, and whether
    a custom tool call is required to answer the question.
    """
    sub_tasks: List[str] = Field(
        ...,
        description="Ordered list of sub-tasks the agents should execute to answer the query."
    )
    category: str = Field(
        ...,
        description="Detected category of the query: exams, fees, library, hostel, academic-calendar, or general."
    )
    requires_tool: bool = Field(
        ...,
        description="Whether the query requires calling the UniversityInfoSearchTool to retrieve context."
    )


class InformationAgentOutput(BaseModel):
    """
    Output schema for the Information/Retrieval Agent.
    Contains the raw answer string, the list of source document references it cited,
    and the resolved category of the query.
    """
    raw_answer: str = Field(
        ...,
        description="The raw textual answer produced by the Information Agent, before validation."
    )
    sources: List[str] = Field(
        default_factory=list,
        description="Source file names or chunk IDs from which the answer was drawn."
    )
    category: str = Field(
        ...,
        description="Detected query category: exams, fees, library, hostel, academic-calendar, or general."
    )


class ValidationResult(BaseModel):
    """
    Output schema for the Validation Agent (implemented with PydanticAI).
    Certifies whether the raw_answer is grounded in the retrieved source chunks,
    flags inaccuracies, attempts a correction, and records a confidence score.
    """
    is_grounded: bool = Field(
        ...,
        description="True if the final answer is supported by the provided source chunks."
    )
    is_accurate: bool = Field(
        ...,
        description="True if the answer contains no factual errors after validation."
    )
    final_answer: str = Field(
        ...,
        description="The corrected or confirmed answer ready to be returned to the user."
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="A 0.0–1.0 confidence score indicating how certain the agent is in the final answer."
    )
    issues: List[str] = Field(
        default_factory=list,
        description="List of specific inaccuracies or hallucinations detected in the raw answer, if any."
    )
